### ISSUE TITLE
BUG : Next.js build fails with window not defined in CookieLocal class.

### ISSUE THREAD

**Issue by chasdevs** [rudderlabs/rudder-sdk-js#517]
**Describe the bug**
When building a next.js project, the CookieLocal class references `window` directly and `next build` fails.

**To Reproduce**
1. Import the rudderstack library per instructions in a next.js project.
2. Run `next build`

**Expected behavior**
The next.js project should build successfully. Instead, this stack trace is given:
```
ReferenceError: window is not defined
   at CookieLocal.options (/app/node_modules/rudder-sdk-js/index.js:9373:43)
   at new CookieLocal (/app/node_modules/rudder-sdk-js/index.js:9358:12)
   at /app/node_modules/rudder-sdk-js/index.js:9449:16
    at /app/node_modules/rudder-sdk-js/index.js:2:66
   at Object.<anonymous> (/app/node_modules/rudder-sdk-js/index.js:5:3)
   at Module._compile (internal/modules/cjs/loader.js:999:30)
   at Object.Module._extensions..js (internal/modules/cjs/loader.js:1027:10)
   at Module.load (internal/modules/cjs/loader.js:863:32)
   at Function.Module._load (internal/modules/cjs/loader.js:708:14)
   at Module.require (internal/modules/cjs/loader.js:887:19) {
  type: 'ReferenceError'
}
```
**Additional Information (please complete the following information):**
- SDK installation: NPM
- NPM Version: 2.5.0

**Desktop (please complete the following information):**
 - OS: macOS Monterey

**Additional context**

**Comment by MoumitaM** [comment]
Hi @chasdevs,

Thank you for bringing this up.
The NPM package needs to be dynamically loaded into the app.
Please check out [this](https://github.com/rudderlabs/rudder-analytics-next/tree/main/sample-next-app-npm) example app.

**Comment by chasdevs** [comment]
Thanks @MoumitaM!
