### ISSUE TITLE
BUG : V2.17.x causes build error when done inside a Docker container

### ISSUE THREAD

**Issue by labithiotis** [rudderlabs/rudder-sdk-js#695]
**Describe the bug**
v 2.17.x causes an error when used with Remix app and installed via a docker container. Error says module is missing.

```sh
✘ [ERROR] Could not resolve "rudder-sdk-js"

    src/providers/AnalyticsProvider.tsx:3:27:
      3 │ import * as analytics from 'rudder-sdk-js';
        ╵                            ~~~~~~~~~~~~~~~

  The path "." is not currently exported by package "rudder-sdk-js":

    ../node_modules/rudder-sdk-js/package.json:7:13:
      7 │   "exports": {
        ╵              ^

  None of the conditions provided ("service-worker") match any of the currently active conditions ("browser", "default", "import"):

    ../node_modules/rudder-sdk-js/package.json:8:9:
      8 │     ".": {
        ╵          ^

  Consider enabling the "service-worker" condition if this package expects it to be enabled. You can use "conditions: ['service-worker']" to do that:

    ../node_modules/rudder-sdk-js/package.json:9:6:
      9 │       "service-worker": "./service-worker/index.es.js"
        ╵       ~~~~~~~~~~~~~~~~

  You can mark the path "rudder-sdk-js" as external to exclude it from the bundle, which will remove this error.


Build failed with 1 error:
src/providers/AnalyticsProvider.tsx:3:27: ERROR: Could not resolve "rudder-sdk-js"
Error
    at Object.onBuildFailure (/usr/src/node_modules/@remix-run/dev/dist/cli/commands.js:183:13)
    at buildEverything (/usr/src/node_modules/@remix-run/dev/dist/compiler.js:282:13)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async Object.build (/usr/src/node_modules/@remix-run/dev/dist/compiler.js:102:3)
    at async Object.build (/usr/src/node_modules/@remix-run/dev/dist/cli/commands.js:178:3)
    at async Object.run (/usr/src/node_modules/@remix-run/dev/dist/cli/run.js:496:7)
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
error Command failed.
Exit code: 1
Command: /usr/local/bin/node
Arguments: /opt/yarn-v1.22.19/lib/cli.js build
Directory: /usr/src/app
Output:

```

**Additional Information (please complete the following information):**
- SDK installation: NPM
- Version:  2.17.x
- Environment: Docker node:16-alpine

**Additional context**
Stepping back to v2.16.0 works

**Comment by bardisg** [comment]
Issue has been identified in package exports. We are proceeding to fix as soon as possible.

Thank you for reporting the issue

**Comment by bardisg** [comment]
Fix is part of the next release now.
